version: 0.0
os: linux
files:
  - source: target/release/
    destination: /home/ec2-user/tordle/target/release
  - source: public/
    destination: /home/ec2-user/tordle/public
  - source: scripts/
    destination: /home/ec2-user/tordle/scripts
  - source: rocket.toml
    destination: /home/ec2-user/tordle/rocket.toml
fileExistsBehavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
  AfterInstall:
    - location: scripts/start-server.sh

