version: 0.2

phases:
  install:
    commands:
      - echo "Installing Rust..."
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustc --version
      - cargo --version
        # - echo "Installing required tools"
        # - rustup component add rustfmt
        # - rustup component add clippy

        # pre_build:
        # commands:
        # - echo "Running format check"
        # - cargo fmt --all -- --check
        # - echo "Running clippy"
        # - cargo clippy --all-targets --all-features -- -D warnings

  build:
    commands:
      - echo "Building the project"
      - cargo build --release

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - target/release/*
    - public/**/*
    - scripts/*
    - appspec.yml
